foreground         #c2c1c2
background         #0D0A0B
background_opacity 1.0
cursor             #c2c1c2

active_tab_foreground     #0D0A0B
active_tab_background     #c2c1c2
inactive_tab_foreground   #c2c1c2
inactive_tab_background   #0D0A0B

active_border_color   #c2c1c2
inactive_border_color #0D0A0B
bell_border_color     #827B7D

color0       #0D0A0B
color8       #695660
color1       #827B7D
color9       #827B7D
color2       #867E81
color10      #867E81
color3       #928C8E
color11      #928C8E
color4       #A29C9E
color12      #A29C9E
color5       #B3AEAF
color13      #B3AEAF
color6       #C2BDBF
color14      #C2BDBF
color7       #c2c1c2
color15      #c2c1c2
